### ISSUE TITLE
AttributeError: module 'torch.nn' has no attribute 'ModuleDict'

### ISSUE THREAD

**Issue by ak9250** [yueruchen/EnlightenGAN#10]
according to this, requirements should be torch==0.4.1?
https://discuss.pytorch.org/t/can-some-one-give-me-a-working-example-of-nn-moduledict/22447/2

**Comment by yueruchen** [comment]
I've updated `requirement.txt`, please check it.

**Comment by Anjali-Poornima666** [comment]
I have installed required libraries from the updated requirement.txt, but still I'm getting the error 
AttributeError: module 'torch.nn' has no attribute 'ModuleDict'

**Comment by yueruchen** [comment]
@Anjali-Poornima666 
Could you please paste the error message here?

**Comment by Anjali-Poornima666** [comment]
class IntermediateLayerGetter(nn.ModuleDict):
AttributeError: module 'torch.nn' has no attribute 'ModuleDict'

**Comment by yueruchen** [comment]
@Anjali-Poornima666 
Could you give a more specific file name and line number?

**Comment by Anjali-Poornima666** [comment]
File
"/home/administrator/users/interns/anjali/EnlightenGAN/data/unaligned_dataset.py",
line 4, in <module>
    import torchvision.transforms as transforms

This is the entire error:

CustomDatasetDataLoader
Traceback (most recent call last):
  File "predict.py", line 16, in <module>
    data_loader = CreateDataLoader(opt)
  File
"/home/administrator/users/interns/anjali/EnlightenGAN/data/data_loader.py",
line 6, in CreateDataLoader
    data_loader.initialize(opt)
  File
"/home/administrator/users/interns/anjali/EnlightenGAN/data/custom_dataset_data_loader.py",
line 39, in initialize
    self.dataset = CreateDataset(opt)
  File
"/home/administrator/users/interns/anjali/EnlightenGAN/data/custom_dataset_data_loader.py",
line 11, in CreateDataset
    from data.unaligned_dataset import UnalignedDataset
  File
"/home/administrator/users/interns/anjali/EnlightenGAN/data/unaligned_dataset.py",
line 4, in <module>
    import torchvision.transforms as transforms
  File
"/home/administrator/users/interns/anjali/pothole/lib/python3.5/site-packages/torchvision/__init__.py",
line 1, in <module>
    from torchvision import models
  File
"/home/administrator/users/interns/anjali/pothole/lib/python3.5/site-packages/torchvision/models/__init__.py",
line 10, in <module>
    from . import segmentation
  File
"/home/administrator/users/interns/anjali/pothole/lib/python3.5/site-packages/torchvision/models/segmentation/__init__.py",
line 1, in <module>
    from .segmentation import *
  File
"/home/administrator/users/interns/anjali/pothole/lib/python3.5/site-packages/torchvision/models/segmentation/segmentation.py",
line 1, in <module>
    from .._utils import IntermediateLayerGetter
  File
"/home/administrator/users/interns/anjali/pothole/lib/python3.5/site-packages/torchvision/models/_utils.py",
line 7, in <module>
    class IntermediateLayerGetter(nn.ModuleDict):
AttributeError: module 'torch.nn' has no attribute 'ModuleDict'

**Comment by yueruchen** [comment]
@Anjali-Poornima666 
I can not reproduce the bug here, if you still meet this problem, I suggest you use pytorch==0.4.1 instead. And you should change the `loss.data[0]` to `loss.item()`.

**Comment by Anjali-Poornima666** [comment]
I'll try with torch 0.4.1
Could you please specify where I should make that change?

**Comment by yueruchen** [comment]
You may consider to look at this page https://pytorch.org/blog/pytorch-0_4_0-migration-guide/

**Comment by mrgloom** [comment]
Same error with:
```
pip freeze | grep torch
torch==0.3.1
torchfile==0.1.0
torchvision==0.3.0
```

**Comment by mrgloom** [comment]
Error is gone with:
```
torch==0.4.1
torchfile==0.1.0
torchvision==0.2.0
```
