### ISSUE TITLE
Google Drive is not reachable

### ISSUE THREAD

**Issue by YangQun1** [yueruchen/EnlightenGAN#12]
Google Drive is not reachable, even if I have used a VPN. Could you please upload the pre-trained model to Baiduyun Drive, or send it to my email(1921296014@qq.com)? Thank you very much!

**Comment by mengjieliu-max** [comment]
me,too.Could you please send the pre-trained model to Baiduyun Drive.,or to my email(1402467549@qq.com)?Thank you!

**Comment by hanxuhfut** [comment]
Baiduyun Drive：link：https://pan.baidu.com/s/11UffhAW-t_7ZvAImIoXiKw 
code：6ft1

**Comment by YangQun1** [comment]
@hanxuhfut Thanks you~

**Comment by laomaup** [comment]
@hanxuhfut   hi， the final_dataset.tar file  has some error when extracting.
gzip: stdin: unexpected end of file
tar: 归档文件中异常的 EOF
tar: 归档文件中异常的 EOF
tar: Error is not recoverable: exiting now

**Comment by hanxuhfut** [comment]
@laomaup  You can do ‘tar -xvf file.tar’ in Linux

**Comment by yueruchen** [comment]
@YangQun1 @mengjieliu-max 
Which one you can not open?

**Comment by yueruchen** [comment]
@laomaup 
I have update new link for training data, please check it.
