### ISSUE TITLE
supplementary materials

### ISSUE THREAD

**Issue by xiaonaa** [yueruchen/EnlightenGAN#13]
Where can I find your supplementary materials? thank you!

**Comment by TemiLee** [comment]
@xiaonaa did you got the supplementary materials?

**Comment by xiaonaa** [comment]
@TemiLee     no

**Comment by yueruchen** [comment]
@xiaonaa @TemiLee 
Supplementary materials will be uploaded soon.

**Comment by TemiLee** [comment]
@yueruchen where the supplementary materials will be upload ? github or the paper in arxiv?

**Comment by yueruchen** [comment]
@TemiLee github

**Comment by TemiLee** [comment]
thanks I am looking forward to it.

**Comment by yueruchen** [comment]
https://ieeexplore.ieee.org/document/9334429/media#media
