### ISSUE TITLE
About your NIQE result

### ISSUE THREAD

**Issue by UtopiaHu** [yueruchen/EnlightenGAN#15]
The test dataset you provided includes NPE dataset and its 3 extensional datasets (data 11, data12, data 13). Are the NIQE scores of NPE dataset (Table 1, column 4) tested only on NPE dataset? or on NPE dataset together with its 3 extensions as a whole ?

**Comment by yueruchen** [comment]
This experiment was conducted so long ago and I need some time to check the detail.
But you could compare the results with a recent work https://arxiv.org/abs/1905.04161. We got nearly the same results which means the experiments setting is also the same.

**Comment by UtopiaHu** [comment]
@yueruchen   Thanks for your reply. By the way, is your network capable of dealing with images with arbitrary size ?

**Comment by yueruchen** [comment]
1. Yes, it is fully convolutional.
2. In the original setting we only random crop 1 patch in a large image. Later we choose to select multiple patches so add another `self.fake_patch_1`, it is a historical problem, sorry.

**Comment by UtopiaHu** [comment]
I see. Thank you

**Comment by UtopiaHu** [comment]
So, if I wanna use the pretrained model to test my own image, I have to feed the image along with its corresponding gray image (self regularization). Am I right ?

**Comment by yueruchen** [comment]
No, it will synthesize the gray image automatically.

**Comment by UtopiaHu** [comment]
I have tested your provided model on all subsets. The NIQE score on VV subset differs greatly from what you have reported in Table 1 (4.799 vs 2.581). Is it normal ?

**Comment by yueruchen** [comment]
I just test it again and got same results, please check your own problem, probably about 1) NIQE implementation (I use the official version. 2) do not change the resolution of test data.

**Comment by UtopiaHu** [comment]
I also used the official code of NIQE. 
When I tested on VV subset, some images can raise the error of insufficient GPU memory. So, did you use at least 2 gpu cards during testing process ?

**Comment by yueruchen** [comment]
@UtopiaHu I used V100 which has 32gb memory. If you want to reproduce our results you need to try a large memory gpu. Or you cloud try to retrain the network with a smaller model (decrese channel number)

**Comment by UtopiaHu** [comment]
I see, thanks

**Comment by LIXINJJ** [comment]
您好，我运行了模型，但是不知道评价指标如何体现出来，请问一下评价指标是将测试完成的图片，单独用代码测试出来的吗？还是将NIQE的评价指标代码加到模型里面。麻烦您解答一下。
