### ISSUE TITLE
which module including the attention map produce

### ISSUE THREAD

**Issue by hhelicopter** [yueruchen/EnlightenGAN#17]
I want to know the attention map and its use in this project. Could you point the location（which module and .py files） of code？

**Comment by UtopiaHu** [comment]
I guess it's in unaligned_dataset.py, A_gray is the self-regularized attention map.

**Comment by Ir1d** [comment]
I think the attention map is the grayscale version of the image

**Comment by hhelicopter** [comment]
> I guess it's in unaligned_dataset.py, A_gray is the self-regularized attention map.
> I think the attention map is the grayscale version of the image

thank you for your answer.But the red box  in the image attached make me confused. Do you know how to achieve it?
![20190716113536](https://user-images.githubusercontent.com/34024905/61264275-88aa5580-a7be-11e9-9f3e-9dc24d6ed64f.png)

**Comment by Ir1d** [comment]
it is skip connection in the code
