### ISSUE TITLE
关于Attention的问题

### ISSUE THREAD

**Issue by sibangde** [yueruchen/EnlightenGAN#18]
文章中说到“We take the illumination channel I of the input RGB image”，RGB图片的Illumination怎么去理解了，从代码中看好像就是RGB图的灰度图，请问是这样吗？

**Comment by Ir1d** [comment]
@jiangzhonglian @wizardforcel 顺便说这个页面没开评论

**Comment by Ir1d** [comment]
@jiangzhonglian @wizardforcel 顺便说这个页面没开评论

**Comment by yueruchen** [comment]
yes
