### ISSUE TITLE
ZeroDivisionError when running script.py with --predict

### ISSUE THREAD

**Issue by htadashi** [yueruchen/EnlightenGAN#19]
Running !python scripts/script.py --predict returns the following error:

> Traceback (most recent call last):
>   File "predict.py", line 25, in <module>
>     for i, data in enumerate(dataset):
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 281, in __next__
>     return self._process_next_batch(batch)
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
>     raise batch.exc_type(batch.exc_msg)
> ZeroDivisionError: Traceback (most recent call last):
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/dataloader.py", line 55, in <listcomp>
>     samples = collate_fn([dataset[i] for i in batch_indices])
>   File "/content/gdrive/My Drive/Colab Notebooks/EnlightenGAN/data/unaligned_dataset.py", line 82, in __getitem__
>     B_img = self.B_imgs[index % self.B_size]
> ZeroDivisionError: integer division or modulo by zero

**Comment by hao-qiang** [comment]
Puting one image in 'test_dataset/testB' folder.

**Comment by htadashi** [comment]
Thanks, the problem is solved :)
