### ISSUE TITLE
the psnr package

### ISSUE THREAD

**Issue by YangQun1** [yueruchen/EnlightenGAN#2]
May I ask, where can I get the psnr package?

**Comment by YangQun1** [comment]
And, could you please upload the pre-trained model?

**Comment by yueruchen** [comment]
psnr package is not used and we found that PSNR/SSIM is not suitable for low light enhancement task.
I'' upload pre-trained model later.

**Comment by YangQun1** [comment]
@yueruchen  thanks，I also found that PSNR or SSIM is not suitable. but, when I use NIQE to evaluate the results, I found that the NIQE score is not stable. May I ask, what model parameters are you use? I use the NIQE code and parameters form this GitHub repo 
https://github.com/dsoellinger/blind_image_quality_toolbox.git

**Comment by YangQun1** [comment]
for example, the CLAHE's results are more poorly in visual quality, but its NIQE score is lower.

**Comment by laomaup** [comment]
thank you,but I can't find the file requirements.txt.

**Comment by yueruchen** [comment]
@YangQun1 
You are right, there isn't suitable metric in this area, NIQE is just a comparably good one. So we use visual results, user study, and non-reference metric to evaluate our method.

**Comment by yueruchen** [comment]
@laomaup 
Sorry, I've updated it already.

**Comment by yueruchen** [comment]
@YangQun1 
NIQE code can be found in its authors' website.
