### ISSUE TITLE
dataset prepareing problem

### ISSUE THREAD

**Issue by fengchaoyu1** [yueruchen/EnlightenGAN#5]
I met a problem when i decompressed you training data. The link files may have been destroyed. Can you share your data with another way or link? Thank you.

**Comment by UtopiaHu** [comment]
I met the same problem

**Comment by fichoo** [comment]
same problem here.
when tar xvf final_dataset.tar shows:
<img width="298" alt="error" src="https://user-images.githubusercontent.com/16023022/60250102-99228b00-98f8-11e9-84c2-1d845138ada3.png">

and after that when running the train.py it shows:

`OSError: image file is truncated`

**Comment by sangenan** [comment]
I also met this problem

**Comment by yueruchen** [comment]
I'll update it soon.

**Comment by yueruchen** [comment]
New training data link is uploaded, please check it
